package view;
/**
 * @web http://jc-mouse.blogspot.com/
 * @author Mouse
 */
public class vista_2 extends javax.swing.JFrame {

    /** Creates new form vista_2 */
    public vista_2() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        vtxt1 = new javax.swing.JTextField();
        vtxt2 = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        vtxt3 = new javax.swing.JTextField();
        cmdsumar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        vtxt1.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        vtxt1.setForeground(new java.awt.Color(255, 51, 0));
        vtxt1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        vtxt1.setText("0");
        vtxt1.setPreferredSize(new java.awt.Dimension(200, 64));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(10, 6, 4, 10);
        jPanel1.add(vtxt1, gridBagConstraints);

        vtxt2.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        vtxt2.setForeground(new java.awt.Color(255, 51, 0));
        vtxt2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        vtxt2.setText("0");
        vtxt2.setPreferredSize(new java.awt.Dimension(200, 64));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(4, 6, 4, 10);
        jPanel1.add(vtxt2, gridBagConstraints);

        jSeparator1.setPreferredSize(new java.awt.Dimension(200, 2));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        jPanel1.add(jSeparator1, gridBagConstraints);

        vtxt3.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        vtxt3.setForeground(new java.awt.Color(255, 51, 0));
        vtxt3.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        vtxt3.setText("0");
        vtxt3.setPreferredSize(new java.awt.Dimension(200, 64));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(4, 6, 10, 10);
        jPanel1.add(vtxt3, gridBagConstraints);

        cmdsumar.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        cmdsumar.setText("+");
        cmdsumar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdsumarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        jPanel1.add(cmdsumar, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdsumarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdsumarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmdsumarActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vista_2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton cmdsumar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    public javax.swing.JTextField vtxt1;
    public javax.swing.JTextField vtxt2;
    public javax.swing.JTextField vtxt3;
    // End of variables declaration//GEN-END:variables

}
